### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by HMwancheng** [jark006/weather_widget#1]
优化小部件默认尺寸，3x1会导致文字重叠/

添加历史1天/未来一周天气

**Comment by jark006** [comment]
> 优化小部件默认尺寸，3x1会导致文字重叠/
> 
> 添加历史1天/未来一周天气
> 

已调整到4*2, 也可手动调整到5*2。暂无计划做历史和未来一周，超过3天的天气预报准确度很低，没啥必要

**Comment by HMwancheng** [comment]
有无按具体坐标显示温度功能

目前貌似是按最近气象站播报，对于部分差距过大地区没有按位置显示天气及温度
（实际19，气象站在另外区县，显示26）

**Comment by jark006** [comment]
> 有无按具体坐标显示温度功能
> 
> 目前貌似是按最近气象站播报，对于部分差距过大地区没有按位置显示天气及温度
> （实际19，气象站在另外区县，显示26）

在app里获取位置信息后，小部件就是使用该位置的经纬度去获取天气信息的，若没有位置信息，默认会使用广州番禺区（广州大学城）的经纬度。

天气数据使用的是彩云天气，数据应该比较准确的，温度应该不会有这么大差距吧

**Comment by HMwancheng** [comment]
不知道哦，我的系统使用的是区县的（26）
下载彩云使用的是经纬度（19）
下载你的显示26

**Comment by HMwancheng** [comment]
![21](https://github.com/user-attachments/assets/be3d850a-0454-41c0-88fb-d09445d73ecd)
截图演示

从上往下分别是
谷歌版彩云 你的小天气  系统自带（中兴）

彩云是准的，现在我都穿两件

**Comment by HMwancheng** [comment]
> 
> 天气数据使用的是彩云天气，数据应该比较准确的，温度应该不会有这么大差距吧

确实有这么大差距awa

**Comment by HMwancheng** [comment]
找到了原因，刷新定位时用的是系统缓存的定位，导致如果没有在新的地方打开过指南针或者导航之类，就会导致定位不准

另外报个 BUG，2×1 的小部件永远会和 4×2 的小部件温度差一度，不多不少一直如此
![Screenshot_20240921_231539](https://github.com/user-attachments/assets/fc248ce8-3ba8-4ba5-8bbc-0156f027ef9b)

**Comment by jark006** [comment]
> 找到了原因，刷新定位时用的是系统缓存的定位，导致如果没有在新的地方打开过指南针或者导航之类，就会导致定位不准
> 
> 另外报个 BUG，2×1 的小部件永远会和 4×2 的小部件温度差一度，不多不少一直如此 ![Screenshot_20240921_231539](https://private-user-images.githubusercontent.com/91036325/369629875-fc248ce8-3ba8-4ba5-8bbc-0156f027ef9b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5MzIyMDAsIm5iZiI6MTcyNjkzMTkwMCwicGF0aCI6Ii85MTAzNjMyNS8zNjk2Mjk4NzUtZmMyNDhjZTgtM2JhOC00YmE1LThiYmMtMDE1NmYwMjdlZjliLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE1MTgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjY2IwYjMyODAzOTQzOWE5NTM3N2FkM2NiODgxYmE3ZGFjZTQzZmRhNGMzYmFmMGIwZDk3YWY4ODU4MTM5N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cOrJ9oNF9P676xDcI-VA4XcYY-G5GQ9GwRJJsmpT3cs)

)

定位用的是高德定位SDK，它的获取、刷新位置信息方式我就不太清楚了。（小部件不会自动刷新位置信息，只能在APP首页手动刷新当前位置信息，小部件会一直使用该位置获取天气数据）

彩云提供的温度是double浮点型，一开始我是直接强转int，例如 26.00 ~ 26.99 都是26度，后来4x2部件改为四舍五入，25.50 ~ 26.49 是26度，但2x1部件忘了改了，我等会改。
