### ISSUE TITLE
在安卓9 机顶盒不显示

### ISSUE THREAD

**Issue by nomoneynolife** [jark006/weather_widget#2]
![00d29f0fc4f3ae75e39dbbdf86b152d](https://github.com/user-attachments/assets/9141a6da-b967-42ef-b2cd-616f56c6074e)

如上图，大佬看看能修复不，需要提供什么

**Comment by nomoneynolife** [comment]
是没有定位引起的不，盒子没有定位功能，可以增加个手动添加位置的按钮不

**Comment by jark006** [comment]
> 是没有定位引起的不，盒子没有定位功能，可以增加个手动添加位置的按钮不

最新版已更新手动编辑位置功能。

2024.10.13 更新 v3.10：
新增手动编辑位置信息
